// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')

function showmsg(msg,type,id)
{

    var html = '<div class="alert ';
    if(type === 0)
    {
        html += ' alert-danger ';
    }
    else
    {
        html += ' alert-success ';
    }
    html += ' alert-dismissible fade in" role="alert" >';
    html += '<button type="button" class="close" data-dismiss="alert"  aria-label="Close">';
    html += '<span aria-hidden="true">&times;</span></button>';
    html += '<strong>消息:</strong> '+msg+'</div>';
    $('#'+id).html(html);
    window.setTimeout(function(){

     $('#'+id).html('');
     },6000);
}